### ISSUE TITLE
Typo in home page

### ISSUE THREAD

**Issue by benas** [javaee/jsonb-spec#59]
Hi,

I noticed a small typo in the example given on the home page here: http://json-b.net/index.html

I guess the Json representation should have `"age": 4` instead of `"age": 3` according to the `Dog` instance shown in the Java code. Or this is intented?

I can open a PR for that if you agree.

Kr
Mahmoud

**Comment by moghaddam** [comment]
Hi Mahmoud

You're right, it's a typo. Feel free to make a PR otherwise I can also fix it ;)

Regards
Ehsan

**Comment by m0mus** [comment]
Fixed & merged. Thank @benas !
